# 9 Numpy

In [1]:
import numpy as numpy
from scipy.linalg import toeplitz

In [2]:
n=200
m= 500
A = numpy.random.normal(0.,1.,(n,m))
'''
toeplitz matrix is a matrix in which each descending diagonal from left to right is constant.
'''
B = toeplitz(numpy.array(list(range(0,m))))

In [3]:
A

array([[ 0.33377699, -0.35671226, -0.20582109, ..., -2.40746906,
         0.42610795, -1.70440578],
       [-0.27804658, -0.44200756, -0.25817729, ...,  0.45923702,
        -0.29812951, -0.07564996],
       [-1.22000621, -1.68309469,  2.37553538, ..., -0.02515178,
         0.95090727, -0.49330235],
       ...,
       [-1.72012765,  0.09952743, -0.68709114, ...,  1.62699531,
         1.5234098 ,  0.35583397],
       [ 0.84882032, -0.34444558,  0.38124813, ...,  0.83722763,
        -0.17940731, -0.10536837],
       [-0.92525654,  0.56920008, -0.10827471, ...,  0.03805825,
        -0.74490903, -0.10747507]])

In [4]:
B

array([[  0,   1,   2, ..., 497, 498, 499],
       [  1,   0,   1, ..., 496, 497, 498],
       [  2,   1,   0, ..., 495, 496, 497],
       ...,
       [497, 496, 495, ...,   0,   1,   2],
       [498, 497, 496, ...,   1,   0,   1],
       [499, 498, 497, ...,   2,   1,   0]])

In [5]:
print(A.shape)
print(B.shape)

(200, 500)
(500, 500)


# Exercise 9.1: Matrix operations 

In [6]:
'''
Calculate A + A, AA>, A>A and AB. Write a function that computes A(B − λI) for any λ.
'''

#A + A
Ex9_1_a = A+A
print("a ----------------")
print(Ex9_1_a)
print("\n\nb ----------------")
#AAT
Ex9_1_b = A.dot(A.T)
print(Ex9_1_b)

#AT.A 
print("\n\nc ----------------")
Ex9_1_c = A.T.dot(A)
print(Ex9_1_c)

#AB
print("\n\nd ----------------")
Ex9_1_d = A.dot(B)
print(Ex9_1_d)

a ----------------
[[ 0.66755397 -0.71342452 -0.41164218 ... -4.81493812  0.8522159
  -3.40881156]
 [-0.55609317 -0.88401513 -0.51635458 ...  0.91847404 -0.59625902
  -0.15129993]
 [-2.44001242 -3.36618938  4.75107076 ... -0.05030356  1.90181455
  -0.9866047 ]
 ...
 [-3.44025529  0.19905487 -1.37418229 ...  3.25399062  3.0468196
   0.71166794]
 [ 1.69764065 -0.68889116  0.76249626 ...  1.67445527 -0.35881461
  -0.21073675]
 [-1.85051307  1.13840016 -0.21654943 ...  0.0761165  -1.48981806
  -0.21495013]]


b ----------------
[[527.65979034   5.46158995 -11.76538684 ... -16.80931109  -8.30082675
    3.9458532 ]
 [  5.46158995 487.59345597   1.56530708 ...  16.14892801   2.67969221
    3.15718512]
 [-11.76538684   1.56530708 534.42806776 ...  -5.394705    -1.23507565
   38.25902967]
 ...
 [-16.80931109  16.14892801  -5.394705   ... 492.12831893  40.41072893
  -14.16246033]
 [ -8.30082675   2.67969221  -1.23507565 ...  40.41072893 503.93403145
   24.35273832]
 [  3.9458532    3.15718512  3

In [7]:
def Ex9_1_e(A,B,lymbda,n):
    return A@(B-lymbda*numpy.eye(n))

In [8]:
Ex9_1_e(A,B,4,500)

array([[ 5408.51321185,  5393.16064413,  5373.72913025, ...,
         3928.50924916,  3938.51361544,  3969.2265606 ],
       [-8744.62540145, -8731.89897064, -8721.44772   , ...,
         2467.54179645,  2458.69214148,  2445.32684317],
       [ 5340.6918516 ,  5321.76967963,  5281.39444406, ...,
         3776.47058268,  3789.98565008,  3815.08360677],
       ...,
       [ 2370.19923821,  2365.70394404,  2371.83279935, ...,
        -5458.47652969, -5468.04425663, -5470.3092027 ],
       [ 3260.46112896,  3252.83865374,  3236.85144891, ...,
         3736.3245962 ,  3755.05386681,  3769.06162732],
       [ 4125.54905953,  4110.87152582,  4106.0201179 , ...,
         -719.87047749,  -708.18464598,  -703.67023753]])

# Exercise 9.2: Solving a linear system

In [9]:
'''
Generate a vector b with m entries and solve Bx = b.
'''
import random
#genereate a vector with m random entries
my_values=[]
for i in range(m):
    my_values.append(random.randint(0,m))
#print(my_values) 
#convert the list to numpy
vector_b=numpy.array(my_values)

#Computes the “exact” solution, x, of the well-determined, i.e., full rank, linear matrix equation ax = b.
x_values=numpy.linalg.solve(B,vector_b)
print("\n\nx_values")
print("The x values are:  ",x_values)



x_values
The x values are:   [-2.26362725e+01 -2.15000000e+01  2.09000000e+02 -3.50500000e+02
  1.63000000e+02  1.74000000e+02 -2.84500000e+02  1.51000000e+02
 -9.50000000e+00  1.45500000e+02 -2.33000000e+02  7.40000000e+01
 -3.40000000e+01  1.68000000e+02 -1.44500000e+02 -1.40000000e+01
 -1.75000000e+01  1.31500000e+02 -2.02500000e+02  1.21500000e+02
 -6.80000000e+01  2.19500000e+02 -2.34000000e+02  2.09000000e+02
 -2.08500000e+02  1.01500000e+02 -1.51500000e+02  1.93000000e+02
  4.45000000e+01 -1.73000000e+02 -5.10000000e+01  1.52500000e+02
  3.40000000e+01 -7.05000000e+01 -1.52000000e+02  2.92000000e+02
 -2.31500000e+02  7.85000000e+01  2.19000000e+02 -4.26500000e+02
  2.34500000e+02  1.65000000e+01  1.19500000e+02 -2.39000000e+02
 -1.80000000e+01  1.68000000e+02  6.75000000e+01 -2.94500000e+02
  1.50000000e+02  7.85000000e+01 -1.60500000e+02  2.71000000e+02
 -1.88000000e+02  5.80000000e+01 -1.66000000e+02  2.19000000e+02
 -1.03500000e+02 -1.21000000e+02  2.75500000e+02 -2.8500000

# Exercise 9.3: Norms

In [10]:
'''
Exercise 9.3: Norms Compute the Frobenius norm of A: |A|F 
and the infinity norm of B: |B|∞. 
Also find the largest and smallest singular values of B.
'''
#a
frobenius_norm_A=numpy.linalg.norm(A,ord=2)
print(frobenius_norm_A)

#b
infinity_norm_B=numpy.linalg.norm(B,ord=numpy.inf)
print(infinity_norm_B)

#c
#singular values of B
unitary_array,singular_values, vh= numpy.linalg.svd(B)
print("The maximum value is {} and the minimum value is {}.".format(max(singular_values),min(singular_values)))

36.24120338818094
124750.0
The maximum value is 86851.66898467173 and the minimum value is 0.5000049348346449.


# Exercise 9.4: Power iteration

In [ ]:
'''
Generate a matrix Z, n × n, with Gaussian entries, and use the power iteration to find the largest
eigenvalue and corresponding eigenvector of Z. How many iterations are needed till convergence?
Optional: use the time.clock() method to compare computation time when varying n.
'''
import time
n=200
def CNM(Z,matrix_u,max_u):
    
    matrix_u = Z@matrix_u
    current = numpy.max(matrix_u)
    diff = numpy.fabs(current-max_u)
    
    return matrix_u,current,diff

def EX9_4(n):
    #Generate a matrix Z, n × n, with Gaussian entries
    Z = numpy.random.normal(0,1,(n,n))

    #The largest eigenvalue is the maximum pole of the system (in terms of magnitude)
    matrix_u = numpy.ones(n).reshape(n,1)

    max_u = numpy.max(matrix_u)
    diff = 1
    
    steps = 0
    #eigenvalues λ of Z is found by solving the equation det(λI−Z)=0
    while True:
        
        if diff<0.05:
            break
            
        #conventional matrix multiplication
        matrix_u,current,diff=CNM(Z,matrix_u,max_u)
        #print(diff)
        max_u = current
        matrix_u = matrix_u / max_u
        steps += 1
    return steps

print("The problem is Solved in: {} steps.".format({EX9_4(n)}))

# Exercise 9.6: Nearest neighbor

In [ ]:
'''
Write a function that takes a value z and an array A and finds the element in A that is closest to z. The
function should return the closest value, not index.
Hint: Use the built-in functionality of Numpy rather than writing code to find this value manually. In
particular, use brackets and argmin.
'''

def EX9_6(A,z):
    if len(A)==0:
        return "Empty List"
    elif len(A)==1:
        return A[0]
    else:
        B = numpy.abs(A - z)
        value=numpy.where(B==numpy.min(B))[0][0]
        return A[value]

A=numpy.array([5,1,7,2, 8,9,12,2])
z=3
print("The Nearest Value to {} is {}.".format(z,EX9_6(A,z)))
