# 10 Scipy

# Exercise 10.1: Least squares

Generate matrix A ∈ Rm×n with m > n. Also generate some vector b ∈ Rm.

*Now find x = arg minx kAx − bk2.

*Print the norm of the residual.

In [101]:
import numpy as np
import scipy.optimize as opt
import math
import scipy.spatial.distance as dis

In [112]:
m, n = 100, 50

def generate_matrix(m,n):
    if n>m:
     return "ERROR: Please assign a correct value for n and m where: m>n!!"
    #generate a random matrix of size n by m
    return np.random.rand(m, n)  

def generate_vector(size):
    #if o is passed, then error. 
    if m==0:
     return "ERROR: Please assign a correct value for m where: m!!"
    #return a vector of size "size"
    return np.random.random(size) 

# generete the matrix A
A = generate_matrix(m,n)
print("Shape of A:\t",A.shape)
# generete the vecotr B
B = np.random.random(m)
print("Shape of B:\t",B.shape)

#finding X
x = opt.lsq_linear(A, B).x

#norm of the residual.
print ("The norm of risidual is:\t",round(np.linalg.norm(B - np.dot(A, x)),5)) 

Shape of A:	 (100, 50)
Shape of B:	 (100,)
The norm of risidual is:	 2.07618


# Exercise 10.2: Optimization

Find the maximum of the function

$f(x) = sin^2(x − 2)e^{-x^2}$

In [113]:

def EX10_2(x):  
    #$f(x) = sin^2(x − 2)$
    sin_square=math.pow(np.sin(x-2), 2)
    #e^{-x^2}
    exp=np.exp(-1*(math.pow(x,2)))
    #since it is the minimum value, then i must return the negative value of it
    return  (sin_square * exp) * -1
    
optiomized_value = opt.minimize_scalar(EX10_2).x
print("The optiomized value is: ",optiomized_value)
#maximum of the function
print(-EX10_2(optiomized_value))

The optiomized value is:  0.2162413285869684
0.9116854118471548


# Exercise 10.3: Pairwise distances

Let X be a matrix with n rows and m columns. How can you compute the pairwise distances between
every two rows?

As an example application, consider n cities, and we are given their coordinates in two columns. Now
we want a nice table that tells us for each two cities, how far they are apart.

Again, make sure you make use of Scipy’s functionality instead of writing your own routine

In [98]:
'''
Let X be a matrix with n rows and m columns. How can you compute the pairwise distances between
every two rows?
'''
n,m=4,5
#generate a random matrix
x_matrix=np.random.rand(n,m)
print(x_matrix)
#calculate the pairwise distances
pairwise_distance = dis.pdist(x_matrix)
print("\n\nPairwise Distance: ",pairwise_distance)
print("\n\nPairwise Distances Are: ")
k=0
#print the pairwise distances
for i in range (n):
    for j in range (i+1,n):
        print("Distance $Elem_{}{}$".format(i,j),pairwise_distance[k])
        k+=1


[[0.19042085 0.6803735  0.95981037 0.47737756 0.23754203]
 [0.43643521 0.50349795 0.49370054 0.78739389 0.81393388]
 [0.96729358 0.10436777 0.6138975  0.64874161 0.16463101]
 [0.72651907 0.28549231 0.93035412 0.61458372 0.89854851]]


Pairwise Distance:  [0.85872237 1.0438636  0.9486597  0.94677426 0.59947014 0.8548245 ]


Pairwise Distances Are: 
Distance $Elem_01$ 0.8587223654425081
Distance $Elem_02$ 1.0438636027676598
Distance $Elem_03$ 0.9486597033580835
Distance $Elem_12$ 0.9467742612051379
Distance $Elem_13$ 0.5994701405449785
Distance $Elem_23$ 0.85482449870572


In [99]:
from scipy.spatial import distance
#generate random cordinates
cordinates = [(np.random.rand(),np.random.rand()) for i in range(n)]
print(cordinates)

#calculate distances between the random generated cordinates
distances=distance.cdist(cordinates,cordinates, 'euclidean')

#printing the table
print("|From|\t\t|To|\t\t|Distance|")
print("----------------------------------------------------")
for i in range (n):
    for j in range (i+1,n):
        
        print("|City_{}|\t|City_{}|\t|{}|".format(i,j,distances[i,j]))
        print("----------------------------------------------------")
        

[(0.6180212567359202, 0.018648225050173717), (0.059965253487682446, 0.6604732090566215), (0.28666703225537926, 0.7408266786642339), (0.014984715436499374, 0.4237992819183781)]
|From|		|To|		|Distance|
----------------------------------------------------
|City_0|	|City_1|	|0.8505091491902212|
----------------------------------------------------
|City_0|	|City_2|	|0.7945673923245882|
----------------------------------------------------
|City_0|	|City_3|	|0.726498760510843|
----------------------------------------------------
|City_1|	|City_2|	|0.24052105224786297|
----------------------------------------------------
|City_1|	|City_3|	|0.24091034969550912|
----------------------------------------------------
|City_2|	|City_3|	|0.417513654339027|
----------------------------------------------------
